### ISSUE TITLE
ValidateIdTokenWithNonce should return the JWTTokenBody

### ISSUE THREAD

**Issue by bigokro** [pagnihotry/siwago#1]
The method does all the work needed to validate the token, which includes extracting the user information provided by Apple. For my app, we will be storing this information with the user's account, so for now we'll have to duplicate this work. It would save us a step if the validation method returned this data for us.

**Comment by pagnihotry** [comment]
Makes sense. I have updated the implementation to include the decoded id token.

**Comment by pagnihotry** [comment]
Feel free to reopen with a comment if it still does not address your issue.

**Comment by bigokro** [comment]
Sorry I didn't respond earlier. I just got around to updating the library today.
Yes! This fix does it for me - 10 lines of duplicate code happily deleted :D
